services:
  django:
    container_name: prototype-django 
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ./backend/db:/app/backend/db
  frontend:
    container_name: prototype-frontend
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on: 
      - django